# Site settings
title: David Mohl
email: me@dave.cx
description: > # this means to ignore newlines until "baseurl:"
    A microblog about technology, programming and the industry. :wq
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dvcrn.github.io" # the base hostname & protocol for your site
twitter_username: davicorn
github_username:  dvcrn

# Build settings
markdown: kramdown
